name: woocomerce
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #state management:
  flutter_riverpod:

  #UI Helpers:
  flutter_spinkit:
  modal_progress_hud:
  get:
  google_fonts:
  carousel_slider:
  smooth_star_rating:
  share:
  #html remove tage
  intl: ^0.17.0
#  fluttertoast:
  fluttertoast: ^8.0.7
  configurable_expansion_tile:
  auto_size_text:




  #localstorage:
  localstorage:
  path_provider:
  build_runner:
  cached_network_image:

  #API:
  woocommerce:

  
  webview_flutter:
  splashscreen:
  uuid:
  font_awesome_flutter:
  cupertino_icons:
#  alert_dialogs:
#    git:
#      url: https://github.com/bizz84/codewithandrea_flutter_packages
#      path: packages/alert_dialogs

dev_dependencies:
  flutter_launcher_icons:
  hive_generator:
  #to build use this command flutter packages pub run build_runner build --delete-conflicting-outputs

  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #    - assets/student.json
    - assets/images/
    - assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages